<?php

/**
 * @file
 * Contains theme overrides and preprocess functions for the HCP Hub theme.
 */

declare(strict_types=1);

use Drupal\Core\Template\Attribute;

/**
 * Implements hook_preprocess_HOOK().
 */
function hcp_hub_preprocess_html(array &$variables): void {
  $classes = [
    'bg-white',
    'text-gray-900',
  ];
  $variables['attributes'] = new Attribute($variables['attributes']);
  $variables['attributes']->addClass($classes);
}
